apiVersion: 1

datasources:
  - name: PostgreSQL Analytics
    type: postgres
    access: proxy
    url: postgres:5432
    database: analytics
    user: postgres
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: postgres
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true
