"""
Solution: Exercise 3.2 -- Fraud Alert Aggregator and Reporter.

A downstream Faust app that consumes fraud alerts, aggregates them per user,
and produces summary reports. Summaries are published every time a user's
alert count crosses a multiple of 3.

Usage:
    faust -A solutions.exercise_03_2_fraud_reporter worker -l info --web-port 6067

    curl http://localhost:6067/fraud/report/
    curl http://localhost:6067/fraud/report/user-0001/

Uses faust-streaming (the maintained community fork), NOT robinhood/faust.
"""

import faust
from datetime import datetime

# ---------------------------------------------------------------------------
# Records
# ---------------------------------------------------------------------------


class FraudAlert(faust.Record):
    """An alert generated by the fraud detection system.

    Attributes:
        transaction_id: The transaction that triggered the alert.
        user_id: The user involved.
        reason: Explanation of why this was flagged.
        risk_score: Numeric risk score from 0.0 to 1.0.
        flagged_at: Timestamp when the alert was created.
    """

    transaction_id: str
    user_id: str
    reason: str
    risk_score: float
    flagged_at: datetime


class FraudSummary(faust.Record):
    """Aggregated fraud summary for a user.

    Attributes:
        user_id: The user this summary is about.
        alert_count: Total number of fraud alerts for this user.
        total_risk_score: Sum of all risk scores.
        avg_risk_score: Average risk score across all alerts.
        reasons: Comma-separated list of the last 5 alert reasons.
        last_alert_at: Timestamp of the most recent alert.
    """

    user_id: str
    alert_count: int
    total_risk_score: float
    avg_risk_score: float
    reasons: str
    last_alert_at: datetime


# ---------------------------------------------------------------------------
# App, Topics, Tables
# ---------------------------------------------------------------------------

app = faust.App(
    "fraud-reporter-app",
    broker="kafka://localhost:9092",
    store="memory://",
    topic_partitions=4,
    value_serializer="json",
)

fraud_alerts_topic = app.topic("fraud-alerts", value_type=FraudAlert, partitions=4)
fraud_summaries_topic = app.topic(
    "fraud-summaries", value_type=FraudSummary, partitions=4
)

# Per-user fraud summary accumulator
fraud_summaries = app.Table("fraud-summaries-table", default=dict)

# ---------------------------------------------------------------------------
# Aggregation Agent
# ---------------------------------------------------------------------------

MAX_REASONS = 5
PUBLISH_INTERVAL = 3  # Publish summary every N alerts


@app.agent(fraud_alerts_topic)
async def aggregate_alerts(stream):
    """Aggregate fraud alerts by user and publish periodic summaries.

    For each incoming alert:
    1. Update the user's summary in the table (count, risk, reasons).
    2. Every 3 alerts, publish a FraudSummary to the output topic.
    """
    async for alert in stream:
        user_id = alert.user_id
        summary = fraud_summaries.get(user_id, {})

        # Update counts
        alert_count = summary.get("alert_count", 0) + 1
        total_risk = summary.get("total_risk_score", 0.0) + alert.risk_score
        avg_risk = total_risk / alert_count

        # Update reasons (keep last 5)
        existing_reasons = summary.get("reasons", "")
        if existing_reasons:
            reasons_list = existing_reasons.split(" | ")
        else:
            reasons_list = []
        reasons_list.append(alert.reason)
        if len(reasons_list) > MAX_REASONS:
            reasons_list = reasons_list[-MAX_REASONS:]
        reasons_str = " | ".join(reasons_list)

        # Store updated summary
        fraud_summaries[user_id] = {
            "alert_count": alert_count,
            "total_risk_score": round(total_risk, 4),
            "avg_risk_score": round(avg_risk, 4),
            "reasons": reasons_str,
            "last_alert_at": alert.flagged_at.isoformat()
            if isinstance(alert.flagged_at, datetime)
            else str(alert.flagged_at),
        }

        print(
            f"[AGGREGATE] user={user_id} "
            f"alerts={alert_count} "
            f"avg_risk={avg_risk:.3f} "
            f"reason={alert.reason}"
        )

        # Publish summary every PUBLISH_INTERVAL alerts
        if alert_count % PUBLISH_INTERVAL == 0:
            fraud_summary = FraudSummary(
                user_id=user_id,
                alert_count=alert_count,
                total_risk_score=round(total_risk, 4),
                avg_risk_score=round(avg_risk, 4),
                reasons=reasons_str,
                last_alert_at=alert.flagged_at
                if isinstance(alert.flagged_at, datetime)
                else datetime.utcnow(),
            )
            await fraud_summaries_topic.send(value=fraud_summary)
            print(
                f"[SUMMARY PUBLISHED] user={user_id} "
                f"alerts={alert_count} avg_risk={avg_risk:.3f}"
            )


# ---------------------------------------------------------------------------
# Summary Sink Agent
# ---------------------------------------------------------------------------


@app.agent(fraud_summaries_topic)
async def log_summaries(stream):
    """Log published fraud summaries."""
    async for summary in stream:
        print(
            f"\n{'='*60}\n"
            f"FRAUD SUMMARY REPORT\n"
            f"  User:           {summary.user_id}\n"
            f"  Alert Count:    {summary.alert_count}\n"
            f"  Avg Risk Score: {summary.avg_risk_score:.3f}\n"
            f"  Total Risk:     {summary.total_risk_score:.3f}\n"
            f"  Recent Reasons: {summary.reasons}\n"
            f"  Last Alert:     {summary.last_alert_at}\n"
            f"{'='*60}\n"
        )


# ---------------------------------------------------------------------------
# Web Views
# ---------------------------------------------------------------------------


@app.page("/fraud/report/")
async def all_reports(web, request):
    """Return all user fraud summaries sorted by alert_count descending."""
    all_summaries = [(k, v) for k, v in fraud_summaries.items()]
    all_summaries.sort(key=lambda x: x[1].get("alert_count", 0), reverse=True)

    report = [
        {"user_id": user_id, **data} for user_id, data in all_summaries
    ]

    return web.json(
        {
            "total_users_flagged": len(report),
            "reports": report,
            "queried_at": datetime.utcnow().isoformat(),
        }
    )


@app.page("/fraud/report/{user_id}/")
async def user_report(web, request, user_id):
    """Return the fraud summary for a specific user."""
    summary = fraud_summaries.get(user_id, {})
    if summary:
        return web.json({"user_id": user_id, **summary})
    else:
        return web.json(
            {
                "user_id": user_id,
                "message": "No fraud alerts recorded for this user",
            }
        )


if __name__ == "__main__":
    app.main()
