"""
SSL Producer - Example Kafka producer configured with SSL/TLS encryption.

This script demonstrates how to configure a Kafka producer with SSL/TLS for
encrypted communication. It references certificates generated by the
config/ssl-setup.sh script.

Prerequisites:
    1. Run the SSL setup script to generate certificates:
       bash config/ssl-setup.sh

    2. Configure Kafka broker with SSL listener (see README.md for details)

Usage:
    python src/ssl_producer.py

    # Custom configuration:
    KAFKA_BOOTSTRAP_SERVERS=localhost:9093 \
    SSL_CA_LOCATION=./ssl/ca-cert.pem \
    SSL_CERT_LOCATION=./ssl/client-cert.pem \
    SSL_KEY_LOCATION=./ssl/client-key.pem \
    TOPIC=ssl-demo \
    python src/ssl_producer.py
"""

import json
import os
import sys
import time
import logging
from datetime import datetime, timezone

from confluent_kafka import Producer, KafkaError

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9093")
TOPIC = os.getenv("TOPIC", "ssl-demo")
NUM_MESSAGES = int(os.getenv("NUM_MESSAGES", "20"))

# SSL certificate paths (generated by config/ssl-setup.sh)
SSL_CA_LOCATION = os.getenv("SSL_CA_LOCATION", "./ssl/ca-cert.pem")
SSL_CERT_LOCATION = os.getenv("SSL_CERT_LOCATION", "./ssl/client-cert.pem")
SSL_KEY_LOCATION = os.getenv("SSL_KEY_LOCATION", "./ssl/client-key.pem")
SSL_KEY_PASSWORD = os.getenv("SSL_KEY_PASSWORD", "")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Certificate validation
# ---------------------------------------------------------------------------


def validate_certificates():
    """
    Check that all required SSL certificate files exist.

    Returns:
        True if all files exist, False otherwise.
    """
    files_to_check = {
        "CA certificate": SSL_CA_LOCATION,
        "Client certificate": SSL_CERT_LOCATION,
        "Client private key": SSL_KEY_LOCATION,
    }

    all_exist = True
    for name, path in files_to_check.items():
        if os.path.exists(path):
            logger.info("  Found %s: %s", name, path)
        else:
            logger.error("  MISSING %s: %s", name, path)
            all_exist = False

    return all_exist


# ---------------------------------------------------------------------------
# Delivery callback
# ---------------------------------------------------------------------------


def delivery_callback(err, msg):
    """
    Called when a message is delivered or delivery fails.

    Args:
        err: Error if delivery failed, None on success.
        msg: The delivered (or failed) message.
    """
    if err is not None:
        logger.error(
            "Delivery failed for %s [%d]: %s",
            msg.topic(), msg.partition(), err,
        )
    else:
        logger.info(
            "Delivered to %s [%d] @ offset %d",
            msg.topic(), msg.partition(), msg.offset(),
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run_ssl_producer():
    """
    Run the SSL-configured Kafka producer.

    Creates a producer with SSL security protocol, validates that certificate
    files exist, and sends a configurable number of test messages.
    """
    logger.info("=" * 60)
    logger.info("SSL Producer Example")
    logger.info("=" * 60)
    logger.info("Configuration:")
    logger.info("  Bootstrap servers: %s", KAFKA_BOOTSTRAP_SERVERS)
    logger.info("  Topic: %s", TOPIC)
    logger.info("  Messages to send: %d", NUM_MESSAGES)
    logger.info("")
    logger.info("SSL Configuration:")

    # Validate certificates exist
    if not validate_certificates():
        logger.error("")
        logger.error("SSL certificates not found. Please run the SSL setup script first:")
        logger.error("  cd config && bash ssl-setup.sh")
        sys.exit(1)

    # Build the producer configuration with SSL settings
    producer_config = {
        # Kafka connection
        "bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS,
        "client.id": "ssl-producer-demo",

        # SSL/TLS configuration
        # security.protocol tells the client to use SSL for all communication
        "security.protocol": "SSL",

        # ssl.ca.location points to the Certificate Authority certificate.
        # The client uses this to verify the broker's certificate is legitimate.
        "ssl.ca.location": SSL_CA_LOCATION,

        # ssl.certificate.location is the client's own certificate.
        # Required for mutual TLS (mTLS) where the broker verifies client identity.
        "ssl.certificate.location": SSL_CERT_LOCATION,

        # ssl.key.location is the client's private key.
        # Used to prove ownership of the client certificate.
        "ssl.key.location": SSL_KEY_LOCATION,

        # Producer settings
        "acks": "all",
        "retries": 3,
    }

    # Add key password if provided
    if SSL_KEY_PASSWORD:
        producer_config["ssl.key.password"] = SSL_KEY_PASSWORD

    logger.info("")
    logger.info("Creating SSL-configured producer...")

    try:
        producer = Producer(producer_config)
        logger.info("Producer created successfully with SSL.")
    except Exception as e:
        logger.error("Failed to create producer: %s", e)
        logger.error("")
        logger.error("Common SSL issues:")
        logger.error("  1. Broker is not configured with SSL listener on port 9093")
        logger.error("  2. Certificate files are corrupt or mismatched")
        logger.error("  3. CA certificate doesn't match the one that signed broker's cert")
        sys.exit(1)

    logger.info("")
    logger.info("Sending %d messages with SSL encryption...", NUM_MESSAGES)
    logger.info("-" * 60)

    for i in range(NUM_MESSAGES):
        message = {
            "message_id": i + 1,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "security": "SSL/TLS encrypted",
            "content": f"Secure message #{i + 1}",
            "producer": "ssl-producer-demo",
        }

        key = f"key-{i % 5}".encode("utf-8")
        value = json.dumps(message).encode("utf-8")

        try:
            producer.produce(
                topic=TOPIC,
                key=key,
                value=value,
                callback=delivery_callback,
            )
        except BufferError:
            logger.warning("Buffer full, waiting...")
            producer.poll(1.0)
            producer.produce(
                topic=TOPIC,
                key=key,
                value=value,
                callback=delivery_callback,
            )

        # Poll for delivery reports
        producer.poll(0)

        # Small delay between messages for readability
        time.sleep(0.1)

    # Flush remaining messages
    logger.info("")
    logger.info("Flushing remaining messages...")
    remaining = producer.flush(timeout=10)

    if remaining > 0:
        logger.warning("%d messages were not delivered", remaining)
    else:
        logger.info("All messages delivered successfully via SSL.")

    logger.info("")
    logger.info("=" * 60)
    logger.info("SSL Producer Example Complete")
    logger.info("=" * 60)


if __name__ == "__main__":
    run_ssl_producer()
