CREATE WAREHOUSE IF NOT EXISTS COMPUTE_DEV
    WAREHOUSE_SIZE    = 'XSMALL'
    AUTO_SUSPEND      = 60
    AUTO_RESUME       = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT           = 'Dev warehouse for ANALYTICS_DEV';