[project]
name = "dqx-demo"
version = "0.1.0"
description = "DQX Demo Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databricks-connect==16.4.1",
    "databricks-labs-dqx>=0.6.0",
    "ipykernel>=6.29.5",
]
